#!/bin/bash
#============================================================
# Terraria 专用服务器一键部署脚本
# 适用于: Ubuntu 22.04+ / Debian 11+
# 主来源: terraria.org Linux dedicated zip
#============================================================

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

TS_USER="${TS_USER:-terraria}"
TS_DIR="${TS_DIR:-/opt/terraria}"
TS_SERVER_DIR="${TS_DIR}/server"
TS_WORLD_DIR="${TS_DIR}/world"
SERVICE_NAME="${SERVICE_NAME:-terraria-server}"
MANAGER_SCRIPT="${MANAGER_SCRIPT:-/usr/local/bin/terraria-manager}"
CREDS_FILE="/etc/terraria/credentials.env"

TS_PORT="${TS_PORT:-7777}"
TS_MAX_PLAYERS="${TS_MAX_PLAYERS:-8}"
TS_SERVER_NAME="${TS_SERVER_NAME:-Terraria Server}"
TS_SERVER_PASSWORD="${TS_SERVER_PASSWORD:-}"
TS_WORLD_NAME="${TS_WORLD_NAME:-world}"
TS_DIFFICULTY="${TS_DIFFICULTY:-1}"
TS_SEED="${TS_SEED:-}"
TS_LANGUAGE="${TS_LANGUAGE:-en-US}"
TS_SECURE="${TS_SECURE:-0}"
TS_MEMORY_MAX="${TS_MEMORY_MAX:-4G}"
TS_VERSION="${TS_VERSION:-}"
NONINTERACTIVE="${NONINTERACTIVE:-0}"

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

write_credentials() {
    mkdir -p "$(dirname "$CREDS_FILE")"
    umask 077
    cat > "$CREDS_FILE" << EOF
# Generated by terraria-server-install.sh
TS_PORT=${TS_PORT}
TS_MAX_PLAYERS=${TS_MAX_PLAYERS}
TS_SERVER_NAME=$(printf '%q' "$TS_SERVER_NAME")
TS_SERVER_PASSWORD=$(printf '%q' "$TS_SERVER_PASSWORD")
TS_WORLD_NAME=$(printf '%q' "$TS_WORLD_NAME")
TS_DIFFICULTY=${TS_DIFFICULTY}
TS_DIR=${TS_DIR}
TS_SERVER_DIR=${TS_SERVER_DIR}
TS_WORLD_DIR=${TS_WORLD_DIR}
SERVICE_NAME=${SERVICE_NAME}
EOF
    chown "root:${TS_USER}" "$CREDS_FILE" 2>/dev/null || chown root:root "$CREDS_FILE"
    chmod 640 "$CREDS_FILE"
    info "配置摘要: ${CREDS_FILE}"
}

check_root() { [[ $EUID -ne 0 ]] && { error "请使用 root 运行"; exit 1; }; }

check_system() {
    [[ -f /etc/os-release ]] && . /etc/os-release || { error "无法检测系统"; exit 1; }
    info "系统: $PRETTY_NAME"
}

check_resources() {
    local cpu mem disk
    cpu=$(nproc)
    mem=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo)
    disk=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
    info "CPU: ${cpu}核 | 内存: ${mem}GB | 磁盘: ${disk}GB"
}

user_config() {
    if [[ "$NONINTERACTIVE" != "1" ]]; then
        echo -e "\n${CYAN}${BOLD}========== Terraria 服务器配置 ==========${NC}\n"
        echo -e "  ┌─────────────────────────────────────────────┐"
        echo -e "  │  1) 服务器名称:  ${TS_SERVER_NAME}"
        echo -e "  │  2) 游戏端口:    ${TS_PORT}"
        echo -e "  │  3) 最大玩家数:  ${TS_MAX_PLAYERS}"
        echo -e "  │  4) 服务器密码:  ${TS_SERVER_PASSWORD:-无}"
        echo -e "  │  5) 难度:        ${TS_DIFFICULTY} (0普通1专家2大师3旅途)"
        echo -e "  │  6) 世界名称:    ${TS_WORLD_NAME}"
        echo -e "  └─────────────────────────────────────────────┘"
        echo ""
        read -rp "  回车使用默认 / 输入 c 自定义: " choice

        if [[ "$choice" == "c" || "$choice" == "C" ]]; then
            read -rp "  服务器名称 [${TS_SERVER_NAME}]: " input
            TS_SERVER_NAME="${input:-$TS_SERVER_NAME}"
            read -rp "  游戏端口 [${TS_PORT}]: " input
            TS_PORT="${input:-$TS_PORT}"
            read -rp "  最大玩家数 [${TS_MAX_PLAYERS}]: " input
            TS_MAX_PLAYERS="${input:-$TS_MAX_PLAYERS}"
            read -rp "  服务器密码 (留空无密码): " input
            TS_SERVER_PASSWORD="${input:-$TS_SERVER_PASSWORD}"
            read -rp "  难度 (0-3) [${TS_DIFFICULTY}]: " input
            TS_DIFFICULTY="${input:-$TS_DIFFICULTY}"
            read -rp "  世界名称 [${TS_WORLD_NAME}]: " input
            TS_WORLD_NAME="${input:-$TS_WORLD_NAME}"
            read -rp "  世界种子 (留空随机): " input
            TS_SEED="${input:-$TS_SEED}"
        fi
    fi
    info "端口: ${TS_PORT} | 世界: ${TS_WORLD_NAME}"
}

install_deps() {
    info "安装依赖..."
    apt-get update -y
    apt-get install -y curl wget unzip ca-certificates python3
}

setup_user() {
    if ! id "$TS_USER" &>/dev/null; then
        useradd -m -r -s /bin/bash "$TS_USER"
    fi
    mkdir -p "$TS_DIR" "$TS_SERVER_DIR" "$TS_WORLD_DIR" "${TS_DIR}/backups"
    chown -R "${TS_USER}:${TS_USER}" "$TS_DIR"
}

find_server_bin() {
    local bin=""
    # Official zip often extracts to <version>/Linux/TerrariaServer.bin.x86_64
    bin=$(find "$TS_SERVER_DIR" -type f \( \
        -name 'TerrariaServer.bin.x86_64' -o \
        -name 'TerrariaServer' -o \
        -name 'TerrariaServer.bin.x86' \
    \) 2>/dev/null | head -1 || true)

    if [[ -z "$bin" ]]; then
        bin=$(find "$TS_SERVER_DIR" -type f -name 'TerrariaServer.exe' 2>/dev/null | head -1 || true)
    fi
    echo "$bin"
}

download_server() {
    info "下载 Terraria Linux 专用服务器（官方 zip）..."

    local latest_version="${TS_VERSION}"
    if [[ -z "$latest_version" ]]; then
        latest_version=$(curl -sL --max-time 15 "https://terraria.org/api/get/download/1" 2>/dev/null | \
            python3 -c "import sys,json; print(json.load(sys.stdin).get('current',''))" 2>/dev/null || true)
    fi
    if [[ -z "$latest_version" ]]; then
        latest_version="1449"
        warn "无法探测最新版本，回退 ${latest_version}"
    fi
    info "Terraria 服务器版本: ${latest_version}"

    local dl_url="https://terraria.org/api/download/pc-dedicated-server/terraria-server-${latest_version}.zip"
    local tmp_zip="/tmp/terraria-server-${latest_version}.zip"
    local staging_dir="${TS_DIR}/server.new"
    mkdir -p "$TS_DIR"

    if ! curl -fL --connect-timeout 20 --retry 3 --retry-delay 5 --max-time 300 -o "$tmp_zip" "$dl_url"; then
        error "下载失败: ${dl_url}"
        exit 1
    fi
    local size
    size=$(stat -c%s "$tmp_zip" 2>/dev/null || echo 0)
    if [[ "$size" -lt 100000 ]]; then
        error "下载文件异常（${size} bytes）"
        exit 1
    fi

    rm -rf "$staging_dir"
    mkdir -p "$staging_dir"
    unzip -o "$tmp_zip" -d "$staging_dir"
    rm -f "$tmp_zip"

    local server_bin
    server_bin=$(find "$staging_dir" -type f \( -name 'TerrariaServer.bin.x86_64' -o -name 'TerrariaServer' -o -name 'TerrariaServer.bin.x86' -o -name 'TerrariaServer.exe' \) 2>/dev/null | head -1 || true)
    if [[ -z "$server_bin" ]]; then
        error "未找到 Terraria 服务器可执行文件，保留现有安装"
        rm -rf "$staging_dir"
        exit 1
    fi

    if [[ -d "$TS_SERVER_DIR" ]]; then
        rm -rf "${TS_DIR}/server.old"
        mv "$TS_SERVER_DIR" "${TS_DIR}/server.old"
    fi
    mv "$staging_dir" "$TS_SERVER_DIR"
    server_bin="${server_bin/$staging_dir/$TS_SERVER_DIR}"

    if [[ "$server_bin" == *.exe ]]; then
        info "安装 Mono 以运行 Windows 二进制..."
        apt-get install -y mono-complete 2>/dev/null || apt-get install -y mono-runtime
    fi

    chmod +x "$server_bin" 2>/dev/null || true
    chown -R "${TS_USER}:${TS_USER}" "$TS_DIR"
    info "服务器可执行文件: ${server_bin}"
    echo "$server_bin" > "${TS_DIR}/.server_bin"
    chown "${TS_USER}:${TS_USER}" "${TS_DIR}/.server_bin"
}

create_server_config() {
    info "创建服务器配置文件..."
    # secure: 0/1 — anti-cheat related; default off unless requested
    cat > "${TS_DIR}/serverconfig.txt" << EOF
# Terraria Server Configuration
world=${TS_WORLD_DIR}/${TS_WORLD_NAME}.wld
worldname=${TS_WORLD_NAME}
autocreate=3
seed=${TS_SEED}
difficulty=${TS_DIFFICULTY}
maxplayers=${TS_MAX_PLAYERS}
port=${TS_PORT}
password=${TS_SERVER_PASSWORD}
secure=${TS_SECURE}
lang=${TS_LANGUAGE}
upnp=0
npcstream=60
motd=Welcome to ${TS_SERVER_NAME}!
EOF
    chown "${TS_USER}:${TS_USER}" "${TS_DIR}/serverconfig.txt"
    chmod 640 "${TS_DIR}/serverconfig.txt"
}

create_start_script() {
    info "创建启动脚本..."
    local server_bin use_mono=false
    server_bin=$(cat "${TS_DIR}/.server_bin" 2>/dev/null || find_server_bin)
    [[ -z "$server_bin" ]] && { error "找不到服务器二进制"; exit 1; }
    [[ "$server_bin" == *.exe ]] && use_mono=true

    cat > "${TS_DIR}/start.sh" << STARTSCRIPT
#!/bin/bash
set -euo pipefail
cd "${TS_DIR}"
SERVER_BIN="${server_bin}"
CONFIG="${TS_DIR}/serverconfig.txt"
USE_MONO=${use_mono}

if \$USE_MONO; then
    exec mono "\$SERVER_BIN" -config "\$CONFIG"
else
    exec "\$SERVER_BIN" -config "\$CONFIG"
fi
STARTSCRIPT

    chmod 750 "${TS_DIR}/start.sh"
    chown "${TS_USER}:${TS_USER}" "${TS_DIR}/start.sh"
}

create_service() {
    info "创建 systemd 服务..."
    cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=Terraria Dedicated Server
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=5

[Service]
Type=simple
User=${TS_USER}
Group=${TS_USER}
WorkingDirectory=${TS_DIR}
ExecStart=${TS_DIR}/start.sh
ExecStop=/bin/kill -SIGINT \$MAINPID
TimeoutStopSec=60
Restart=on-failure
RestartSec=10
MemoryMax=${TS_MEMORY_MAX}
OOMScoreAdjust=-500
ProtectSystem=strict
ReadWritePaths=${TS_DIR}
PrivateTmp=true
NoNewPrivileges=true
StandardOutput=journal
StandardError=journal
SyslogIdentifier=terraria

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}"
}

create_manager() {
    info "创建管理脚本..."
    cat > "${MANAGER_SCRIPT}" << 'MANAGEREOF'
#!/bin/bash
set -euo pipefail
CREDS_FILE="/etc/terraria/credentials.env"
# shellcheck disable=SC1090
[[ -f "$CREDS_FILE" ]] && source "$CREDS_FILE"
SERVICE="${SERVICE_NAME:-terraria-server}"
TS_DIR="${TS_DIR:-/opt/terraria}"
TS_PORT="${TS_PORT:-7777}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

show_help() {
    echo -e "${CYAN}Terraria 服务器管理工具${NC}"
    echo "用法: terraria-manager <start|stop|restart|status|logs|console|backup|config|info>"
}

cmd_start()   { systemctl start "$SERVICE" && echo -e "${GREEN}已启动${NC}"; }
cmd_stop()    { systemctl stop "$SERVICE" && echo -e "${YELLOW}已停止${NC}"; }
cmd_restart() { systemctl restart "$SERVICE" && echo -e "${GREEN}已重启${NC}"; }
cmd_status()  { systemctl status "$SERVICE" --no-pager; }
cmd_logs()    { journalctl -u "$SERVICE" -f --no-pager; }

cmd_console() {
    echo -e "${YELLOW}systemd 直接管理 Terraria 进程，不提供可附着控制台。${NC}"
    echo "实时输出: journalctl -u $SERVICE -f"
    return 1
}

cmd_backup() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}备份需要 root${NC}" >&2
        exit 1
    fi
    local backup_dir="${TS_DIR}/backups"
    local ts file
    ts=$(date +%Y%m%d_%H%M%S)
    file="${backup_dir}/terraria_backup_${ts}.tar.gz"
    mkdir -p "$backup_dir"
    local was_active=false
    systemctl is-active --quiet "$SERVICE" && was_active=true
    if $was_active; then
        systemctl stop "$SERVICE"
        sleep 3
    fi
    if ! tar -czf "$file" -C "${TS_DIR}" world serverconfig.txt; then
        $was_active && systemctl start "$SERVICE" || true
        echo -e "${RED}备份失败${NC}" >&2
        return 1
    fi
    $was_active && systemctl start "$SERVICE" || true
    echo -e "${GREEN}备份: ${file}${NC}"
    ls -t "${backup_dir}"/terraria_backup_*.tar.gz 2>/dev/null | tail -n +21 | xargs -r rm -f
}

cmd_config() {
    ${EDITOR:-nano} "${TS_DIR}/serverconfig.txt"
    echo -e "${YELLOW}重启生效: terraria-manager restart${NC}"
}

cmd_info() {
    local ip
    ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    echo -e "${CYAN}=== Terraria 服务器 ===${NC}"
    echo "地址:   ${ip}:${TS_PORT}"
    echo "状态:   $(systemctl is-active "$SERVICE")"
    echo "配置:   ${TS_DIR}/serverconfig.txt"
}

case "${1:-help}" in
    start) cmd_start ;; stop) cmd_stop ;; restart) cmd_restart ;;
    status) cmd_status ;; logs) cmd_logs ;; console) cmd_console ;;
    backup) cmd_backup ;; config) cmd_config ;; info) cmd_info ;; *) show_help ;;
esac
MANAGEREOF
    chmod 750 "${MANAGER_SCRIPT}"
}

create_backup_timer() {
    cat > "/etc/systemd/system/${SERVICE_NAME}-backup.service" << EOF
[Unit]
Description=Terraria Server Backup
[Service]
Type=oneshot
ExecStart=${MANAGER_SCRIPT} backup
User=root
EOF

    cat > "/etc/systemd/system/${SERVICE_NAME}-backup.timer" << EOF
[Unit]
Description=Backup Terraria every 6 hours
[Timer]
OnCalendar=*-*-* 00,06,12,18:00:00
Persistent=true
RandomizedDelaySec=60
[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now "${SERVICE_NAME}-backup.timer"
    info "每6小时自动备份已启用（root）"
}

setup_firewall() {
    if command -v ufw &>/dev/null; then
        ufw allow "${TS_PORT}/tcp" comment "Terraria Server"
        if ufw status 2>/dev/null | grep -qi "Status: active"; then
            info "UFW 已生效，放行 TCP ${TS_PORT}"
        else
            warn "UFW 规则已添加，但 UFW 当前未启用"
        fi
    elif command -v firewall-cmd &>/dev/null; then
        firewall-cmd --permanent --add-port="${TS_PORT}/tcp"
        firewall-cmd --reload
    else
        warn "请手动开放 TCP ${TS_PORT}"
    fi
}

start_server() {
    info "启动 Terraria 服务器..."
    if systemctl is-active --quiet "${SERVICE_NAME}"; then
        systemctl restart "${SERVICE_NAME}"
    else
        systemctl start "${SERVICE_NAME}"
    fi
    sleep 8
    systemctl is-active --quiet "${SERVICE_NAME}" && info "启动成功!" || warn "请等待初始化... journalctl -u ${SERVICE_NAME} -f"
}

show_result() {
    local ip
    ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    echo ""
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo -e "${GREEN}${BOLD}       Terraria 服务器部署完成!${NC}"
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo ""
    echo -e "  服务器地址:  ${CYAN}${ip}:${TS_PORT}${NC}"
    echo -e "  配置文件:    ${TS_DIR}/serverconfig.txt"
    echo -e "  世界目录:    ${TS_WORLD_DIR}/"
    echo -e "  管理: terraria-manager start|stop|restart|status|logs|console|backup|config|info"
    echo ""
    echo -e "  ${RED}${BOLD}云安全组请放行 TCP ${TS_PORT}${NC}"
    echo -e "${GREEN}${BOLD}============================================================${NC}"
}

main() {
    echo -e "${CYAN}${BOLD}"
    echo "  ╔╦╗╔═╗╔═╗╔═╗╔═╗╦═╗╔╦╗"
    echo "   ║ ║╣ ╠═╣╚═╗║╣ ╠╦╝║║║"
    echo "   ╩ ╩ ╩╩ ╩╚═╝╚═╝╩╚═╩ ╩"
    echo -e "    Dedicated Server Installer${NC}"
    echo ""

    check_root
    check_system
    check_resources
    user_config

    if [[ "$NONINTERACTIVE" != "1" ]]; then
        read -rp "回车开始部署 / 输入 n 取消: " confirm
        [[ "$confirm" == "n" || "$confirm" == "N" ]] && { echo "已取消"; exit 0; }
    fi

    install_deps
    setup_user
    write_credentials
    download_server
    create_server_config
    create_start_script
    create_service
    create_manager
    create_backup_timer
    setup_firewall
    start_server
    show_result
}

main "$@"
