#!/bin/bash
#============================================================
# Valheim 专用服务器一键部署脚本
# 适用于: Ubuntu 22.04+ / Debian 11+
# SteamCMD AppID: 896660
#============================================================

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

VH_USER="${VH_USER:-valheim}"
VH_DIR="${VH_DIR:-/opt/valheim}"
VH_SERVER_DIR="${VH_DIR}/server"
VH_WORLD_DIR="${VH_DIR}/world"
SERVICE_NAME="${SERVICE_NAME:-valheim-server}"
MANAGER_SCRIPT="${MANAGER_SCRIPT:-/usr/local/bin/valheim-manager}"
CREDS_FILE="/etc/valheim/credentials.env"

VH_SERVER_NAME="${VH_SERVER_NAME:-Valheim Server}"
VH_SERVER_PORT="${VH_SERVER_PORT:-2456}"
VH_QUERY_PORT=""
VH_WORLD_NAME="${VH_WORLD_NAME:-Dedicated}"
VH_SERVER_PASSWORD="${VH_SERVER_PASSWORD:-}"
VH_PUBLIC="${VH_PUBLIC:-1}"
VH_CROSSPLAY="${VH_CROSSPLAY:-false}"
VH_MEMORY_MAX="${VH_MEMORY_MAX:-14G}"
NONINTERACTIVE="${NONINTERACTIVE:-0}"

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

gen_password() {
    local p
    p=$(set +o pipefail; head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo "${p:-vh$(date +%s)}"
}

write_credentials() {
    mkdir -p "$(dirname "$CREDS_FILE")"
    umask 077
    cat > "$CREDS_FILE" << EOF
# Generated by valheim-server-install.sh — root:root 600
VH_SERVER_NAME=$(printf '%q' "$VH_SERVER_NAME")
VH_SERVER_PORT=${VH_SERVER_PORT}
VH_QUERY_PORT=${VH_QUERY_PORT}
VH_WORLD_NAME=$(printf '%q' "$VH_WORLD_NAME")
VH_SERVER_PASSWORD=$(printf '%q' "$VH_SERVER_PASSWORD")
VH_PUBLIC=${VH_PUBLIC}
VH_CROSSPLAY=${VH_CROSSPLAY}
VH_DIR=${VH_DIR}
VH_SERVER_DIR=${VH_SERVER_DIR}
VH_WORLD_DIR=${VH_WORLD_DIR}
SERVICE_NAME=${SERVICE_NAME}
EOF
    chown root:root "$CREDS_FILE"
    chmod 600 "$CREDS_FILE"
    info "凭证已写入 ${CREDS_FILE} (root:root 600)"
}

check_root() {
    [[ $EUID -ne 0 ]] && { error "请使用 root 运行: sudo bash $0"; exit 1; }
}

check_system() {
    [[ -f /etc/os-release ]] && . /etc/os-release || { error "无法检测系统"; exit 1; }
    info "系统: $PRETTY_NAME"
}

check_resources() {
    local cpu mem disk
    cpu=$(nproc)
    mem=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo)
    disk=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
    info "CPU: ${cpu}核 | 内存: ${mem}GB | 磁盘: ${disk}GB"
    [[ $mem -lt 4 ]] && warn "内存不足 4GB，建议至少 4GB"
}

user_config() {
    if [[ -z "$VH_SERVER_PASSWORD" ]]; then
        VH_SERVER_PASSWORD="$(gen_password)"
        info "已自动生成服务器密码（长度 ${#VH_SERVER_PASSWORD}）"
    fi

    if [[ "$NONINTERACTIVE" != "1" ]]; then
        echo -e "\n${CYAN}${BOLD}========== Valheim 服务器配置 ==========${NC}\n"
        echo -e "  ┌─────────────────────────────────────────────┐"
        echo -e "  │  1) 服务器名称:  ${VH_SERVER_NAME}"
        echo -e "  │  2) 服务器密码:  (已设置，安装结束显示)"
        echo -e "  │  3) 世界名称:    ${VH_WORLD_NAME}"
        echo -e "  │  4) 游戏端口:    ${VH_SERVER_PORT}"
        echo -e "  │  5) 公开服务器:  ${VH_PUBLIC}"
        echo -e "  │  6) 跨平台:      ${VH_CROSSPLAY}"
        echo -e "  └─────────────────────────────────────────────┘"
        echo ""
        read -rp "  回车使用默认 / 输入 c 自定义: " choice

        if [[ "$choice" == "c" || "$choice" == "C" ]]; then
            read -rp "  服务器名称 [${VH_SERVER_NAME}]: " input
            VH_SERVER_NAME="${input:-$VH_SERVER_NAME}"
            read -rp "  服务器密码 (至少5位，回车保留当前): " input
            [[ -n "${input:-}" ]] && VH_SERVER_PASSWORD="$input"
            read -rp "  世界名称 [${VH_WORLD_NAME}]: " input
            VH_WORLD_NAME="${input:-$VH_WORLD_NAME}"
            read -rp "  游戏端口 [${VH_SERVER_PORT}]: " input
            VH_SERVER_PORT="${input:-$VH_SERVER_PORT}"
            read -rp "  公开服务器 (0/1) [${VH_PUBLIC}]: " input
            VH_PUBLIC="${input:-$VH_PUBLIC}"
            read -rp "  跨平台 (true/false) [${VH_CROSSPLAY}]: " input
            VH_CROSSPLAY="${input:-$VH_CROSSPLAY}"
        fi
    fi

    if [[ ${#VH_SERVER_PASSWORD} -lt 5 ]]; then
        error "Valheim 服务器密码至少需要 5 个字符"
        exit 1
    fi

    VH_QUERY_PORT=$((VH_SERVER_PORT + 1))
    info "端口: 游戏 ${VH_SERVER_PORT} / 查询 ${VH_QUERY_PORT}"
}

install_deps() {
    info "安装依赖..."
    dpkg --add-architecture i386 2>/dev/null || true
    apt-get update -y
    apt-get install -y curl ca-certificates lib32gcc-s1 libc6:i386 libstdc++6:i386
}

install_steamcmd() {
    if command -v steamcmd &>/dev/null; then
        info "SteamCMD 已安装"
        return
    fi
    info "安装 SteamCMD..."
    apt-get install -y steamcmd 2>/dev/null || {
        local dir="/opt/steamcmd"
        local archive="/tmp/steamcmd_linux.tar.gz"
        mkdir -p "$dir"
        curl -fL --connect-timeout 20 --retry 3 --retry-delay 5 \
            "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" -o "$archive"
        tar -xzf "$archive" -C "$dir"
        rm -f "$archive"
        ln -sf "${dir}/steamcmd.sh" /usr/bin/steamcmd
    }
    [[ -f /usr/games/steamcmd ]] && ln -sf /usr/games/steamcmd /usr/bin/steamcmd
    info "SteamCMD 安装完成"
}

setup_user() {
    if ! id "$VH_USER" &>/dev/null; then
        useradd -m -r -s /bin/bash "$VH_USER"
    fi
    mkdir -p "$VH_DIR" "$VH_SERVER_DIR" "$VH_WORLD_DIR" "${VH_DIR}/backups" "${VH_SERVER_DIR}/logs"
    chown -R "${VH_USER}:${VH_USER}" "$VH_DIR"
}

download_server() {
    info "下载 Valheim 专用服务器 (AppID: 896660)..."
    chown "${VH_USER}:${VH_USER}" "$VH_SERVER_DIR"

    local retry=0
    while ! sudo -u "$VH_USER" steamcmd +login anonymous +force_install_dir "$VH_SERVER_DIR" +app_update 896660 validate +quit; do
        retry=$((retry + 1))
        [[ $retry -ge 3 ]] && { error "下载失败"; exit 1; }
        warn "重试 ${retry}/3..."
        sleep 5
    done

    if [[ -f "${VH_SERVER_DIR}/valheim_server.x86_64" ]]; then
        info "下载完成"
    else
        error "服务器文件缺失: valheim_server.x86_64"
        exit 1
    fi
}

create_start_script() {
    info "创建启动脚本（从 credentials.env 读取配置）..."

    cat > "${VH_DIR}/start.sh" << 'STARTSCRIPT'
#!/bin/bash
set -euo pipefail
CREDS_FILE="/etc/valheim/credentials.env"
# shellcheck disable=SC1090
source "$CREDS_FILE"

export templdpath="${LD_LIBRARY_PATH:-}"
export LD_LIBRARY_PATH=./linux64:${LD_LIBRARY_PATH:-}
export SteamAppId=892970

cd "${VH_SERVER_DIR}"
mkdir -p logs

CROSSPLAY_ARG=()
if [[ "${VH_CROSSPLAY}" == "true" ]]; then
    CROSSPLAY_ARG=(-crossplay)
fi

exec ./valheim_server.x86_64 \
    -name "${VH_SERVER_NAME}" \
    -port "${VH_SERVER_PORT}" \
    -world "${VH_WORLD_NAME}" \
    -password "${VH_SERVER_PASSWORD}" \
    -public "${VH_PUBLIC}" \
    "${CROSSPLAY_ARG[@]}" \
    -savedir "${VH_WORLD_DIR}" \
    -logFile "${VH_SERVER_DIR}/logs/valheim-$(date +%Y%m%d).log"
STARTSCRIPT

    chmod 750 "${VH_DIR}/start.sh"
    chown "root:${VH_USER}" "${VH_DIR}/start.sh"
    # start.sh needs to read credentials; grant group read via ACL-like ownership:
    # credentials are root:root 600 — start runs as VH_USER so must allow read.
    # Grant valheim group read on credentials instead of world-readable.
    chown "root:${VH_USER}" "$CREDS_FILE"
    chmod 640 "$CREDS_FILE"
}

create_service() {
    info "创建 systemd 服务..."
    cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=Valheim Dedicated Server
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=5

[Service]
Type=simple
User=${VH_USER}
Group=${VH_USER}
WorkingDirectory=${VH_SERVER_DIR}
ExecStart=${VH_DIR}/start.sh
ExecStop=/bin/kill -SIGINT \$MAINPID
Restart=on-failure
RestartSec=10
TimeoutStopSec=120
MemoryMax=${VH_MEMORY_MAX}
OOMScoreAdjust=-500
ProtectSystem=strict
ReadWritePaths=${VH_DIR}
PrivateTmp=true
NoNewPrivileges=true
StandardOutput=journal
StandardError=journal
SyslogIdentifier=valheim

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}"
}

create_manager() {
    info "创建管理脚本..."
    cat > "${MANAGER_SCRIPT}" << 'MANAGEREOF'
#!/bin/bash
set -euo pipefail
CREDS_FILE="/etc/valheim/credentials.env"
# shellcheck disable=SC1090
source "$CREDS_FILE"
SERVICE="${SERVICE_NAME}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

show_help() {
    echo -e "${CYAN}Valheim 服务器管理工具${NC}"
    echo "用法: valheim-manager <start|stop|restart|status|logs|backup|update|info>"
}

cmd_start()   { systemctl start "$SERVICE" && echo -e "${GREEN}已启动${NC}"; }
cmd_stop()    { systemctl stop "$SERVICE" && echo -e "${YELLOW}已停止${NC}"; }
cmd_restart() { systemctl restart "$SERVICE" && echo -e "${GREEN}已重启${NC}"; }
cmd_status()  { systemctl status "$SERVICE" --no-pager; }
cmd_logs()    { journalctl -u "$SERVICE" -f --no-pager; }

cmd_backup() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}备份需要 root（需 systemctl 与写备份目录）${NC}" >&2
        exit 1
    fi
    local backup_dir="${VH_DIR}/backups"
    local ts file
    ts=$(date +%Y%m%d_%H%M%S)
    file="${backup_dir}/valheim_backup_${ts}.tar.gz"
    mkdir -p "$backup_dir"
    local was_active=false
    systemctl is-active --quiet "$SERVICE" && was_active=true
    if $was_active; then
        systemctl stop "$SERVICE"
        sleep 3
    fi
    if ! tar -czf "$file" -C "${VH_DIR}" world; then
        $was_active && systemctl start "$SERVICE" || true
        echo -e "${RED}备份失败${NC}" >&2
        return 1
    fi
    chown "${VH_USER:-valheim}:${VH_USER:-valheim}" "$file" 2>/dev/null || true
    $was_active && systemctl start "$SERVICE" || true
    echo -e "${GREEN}备份: ${file}${NC}"
    ls -t "${backup_dir}"/valheim_backup_*.tar.gz 2>/dev/null | tail -n +21 | xargs -r rm -f
}

cmd_update() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}更新需要 root${NC}" >&2
        exit 1
    fi
    echo -e "${CYAN}更新中...${NC}"
    local was_active=false
    systemctl is-active --quiet "$SERVICE" && was_active=true
    systemctl stop "$SERVICE" || true
    if ! sudo -u valheim steamcmd +login anonymous +force_install_dir "$VH_SERVER_DIR" +app_update 896660 validate +quit; then
        echo -e "${RED}更新失败${NC}" >&2
        $was_active && systemctl start "$SERVICE" || true
        return 1
    fi
    systemctl start "$SERVICE"
    echo -e "${GREEN}更新完成${NC}"
}

cmd_info() {
    local ip
    ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    echo -e "${CYAN}=== Valheim 服务器 ===${NC}"
    echo "地址:   ${ip}:${VH_SERVER_PORT}"
    echo "查询:   ${ip}:${VH_QUERY_PORT}"
    echo "世界:   ${VH_WORLD_NAME}"
    echo "状态:   $(systemctl is-active "$SERVICE")"
    echo "凭证:   ${CREDS_FILE}"
}

case "${1:-help}" in
    start) cmd_start ;; stop) cmd_stop ;; restart) cmd_restart ;;
    status) cmd_status ;; logs) cmd_logs ;; backup) cmd_backup ;;
    update) cmd_update ;; info) cmd_info ;; *) show_help ;;
esac
MANAGEREOF
    chmod 750 "${MANAGER_SCRIPT}"
}

create_backup_timer() {
    cat > "/etc/systemd/system/${SERVICE_NAME}-backup.service" << EOF
[Unit]
Description=Valheim Server Backup
[Service]
Type=oneshot
ExecStart=${MANAGER_SCRIPT} backup
User=root
EOF

    cat > "/etc/systemd/system/${SERVICE_NAME}-backup.timer" << EOF
[Unit]
Description=Backup Valheim every 6 hours
[Timer]
OnCalendar=*-*-* 00,06,12,18:00:00
Persistent=true
RandomizedDelaySec=60
[Install]
WantedBy=timers.target
EOF

    systemctl daemon-reload
    systemctl enable --now "${SERVICE_NAME}-backup.timer"
    info "每6小时自动备份已启用（以 root 运行）"
}

setup_firewall() {
    if command -v ufw &>/dev/null; then
        ufw allow "${VH_SERVER_PORT}/udp" comment "Valheim Game"
        ufw allow "${VH_QUERY_PORT}/udp" comment "Valheim Query"
        if ufw status 2>/dev/null | grep -qi "Status: active"; then
            info "UFW 已生效，放行 UDP ${VH_SERVER_PORT}-${VH_QUERY_PORT}"
        else
            warn "UFW 规则已添加，但 UFW 当前未启用 (ufw status)"
        fi
    elif command -v firewall-cmd &>/dev/null; then
        firewall-cmd --permanent --add-port="${VH_SERVER_PORT}-${VH_QUERY_PORT}/udp"
        firewall-cmd --reload
    else
        warn "请手动开放 UDP ${VH_SERVER_PORT}-${VH_QUERY_PORT}"
    fi
}

start_server() {
    info "启动 Valheim 服务器..."
    if systemctl is-active --quiet "${SERVICE_NAME}"; then
        systemctl restart "${SERVICE_NAME}"
    else
        systemctl start "${SERVICE_NAME}"
    fi
    sleep 10
    systemctl is-active --quiet "${SERVICE_NAME}" && info "启动成功!" || warn "请等待初始化... journalctl -u ${SERVICE_NAME} -f"
}

show_result() {
    local ip
    ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    echo ""
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo -e "${GREEN}${BOLD}       Valheim 服务器部署完成!${NC}"
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo ""
    echo -e "  服务器地址:  ${CYAN}${ip}:${VH_SERVER_PORT}${NC}"
    echo -e "  查询端口:    ${CYAN}${VH_QUERY_PORT}${NC}"
    echo -e "  服务器密码:  ${CYAN}${VH_SERVER_PASSWORD}${NC}"
    echo -e "  世界名称:    ${CYAN}${VH_WORLD_NAME}${NC}"
    echo -e "  凭证文件:    ${CYAN}${CREDS_FILE}${NC} (root:${VH_USER} 640)"
    echo ""
    echo -e "  管理: valheim-manager start|stop|restart|status|logs|backup|update|info"
    echo ""
    echo -e "  ${RED}${BOLD}云安全组请放行 UDP ${VH_SERVER_PORT} 与 ${VH_QUERY_PORT}${NC}"
    echo -e "${GREEN}${BOLD}============================================================${NC}"
}

main() {
    echo -e "${CYAN}${BOLD}"
    echo "  ╦  ╦╔═╗╔═╗╦  ╦╔╦╗╔═╗"
    echo "  ╚╗╔╝╠═╣╠═╝║  ║ ║ ║╣ "
    echo "   ╚╝ ╩ ╩╩  ╩══╩ ╩ ╚═╝"
    echo -e "    Dedicated Server Installer${NC}"
    echo ""

    check_root
    check_system
    check_resources
    user_config
    write_credentials

    if [[ "$NONINTERACTIVE" != "1" ]]; then
        read -rp "回车开始部署 / 输入 n 取消: " confirm
        [[ "$confirm" == "n" || "$confirm" == "N" ]] && { echo "已取消"; exit 0; }
    fi

    install_deps
    install_steamcmd
    setup_user
    download_server
    create_start_script
    create_service
    create_manager
    create_backup_timer
    setup_firewall
    start_server
    show_result
}

main "$@"
